paper.pdf: paper.tex ../thebib.bib HprimeDef.tex Ex42.tex Ex42a.tex \
            Ex42b.tex Ex42c.tex Ex42d.tex Ex42e.tex
	 pdflatex paper; bibtex paper; pdflatex paper; pdflatex paper


#### Note: origin of the snippets (manually copied *)
#### ../movies/snippets/Schutte :
####    Ex42a.texEx42b.tex EX42c.tex Ex42d.tex Ex42e.tex
#### ../movies/snippets/Hprime/HprimeDef.tex
#### ../movies/snippets/E0/Ex42.tex
